### ISSUE TITLE
Fix "Two-Factor Authentication" view console errors

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-two-factor#127] opened 2023-04-21 06:00 UTC
## Errors

```
react-dom.js?ver=18:1 Warning: React does not recognize the `setInputs` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `setinputs` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
...
react-dom.js?ver=18:1 Warning: Unknown event handler property `onComplete`. It will be ignored.
   ```

**Comment by iandunn** [comment] 2023-05-11 23:42
#152 is a duplicate of this, but I missed that when opening it. I'm gonna leave that one open since it has more info and is tied to the PR.

**Closed as completed by iandunn** 2023-05-11 23:42 UTC
Labels: priority: low
